Description of create
Home > .. > SMASHtoolbox > +SMASH > +SignalAnalysis > @STFT > old > create.m
create
PURPOSE
SYNOPSIS
function object=create(object,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
create
initialize
This function is called by:
create
SOURCE CODE
function object=create(object,varargin)
object=create@SMASH.SignalAnalysis.ShortTime(object,varargin{:});
object=initialize(object);
end