Description of local_uicontrol
Home > .. > SMASHtoolbox > +SMASH > +MUI > @Dialog > private > local_uicontrol.m
local_uicontrol
PURPOSE
% local uicontrol (could be pushed out to separate classes
SYNOPSIS
function varargout=local_uicontrol(object,varargin)
DESCRIPTION
% local uicontrol (could be pushed out to separate classes
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
button dialog.button : add button block to dialog
cedit handle input
cedit_button Usage:
cedit_check dialog.cedit_check : add edit/check block to dialog
check dialog.check : add check block to dialog
edit handle input
edit_button Usage:
edit_check dialog.edit_check : add edit/check block to dialog
listbox dialog.popup : add popup block to dialog
listbox_button dialog.listbox_button : add listbox with button(s) block to dialog
medit handle input
popup dialog.popup : add popup block to dialog
popup_button dialog.popup_button : add popup/button block to dialog
radio dialog.radio : add radio block to dialog
slider handle input
table handle input
text handle input
toggle dialog.toggle : add toggle block to dialog
SOURCE CODE
%% local uicontrol (could be pushed out to separate classes
function varargout=local_uicontrol(object,varargin)
% create uicontrol
h=uicontrol('Parent',object.Handle,'Units','pixels');
set(h,varargin{:});
extent=get(h,'Extent');
position=[object.HorizontalMargin object.VerticalMargin extent(3:4)];
set(h,'Position',position);
% style-specific tweaks
style=get(h,'Style');
switch style
    case {'pushbutton','togglebutton'}
        position(4)=1.50*position(4);
        set(h,'Position',position);
    case 'checkbox'
    case 'text'
        parent=get(h,'Parent');
        color=get(parent,'Color');
        set(h,'BackgroundColor',color);
    case 'edit'
        set(h,'BackgroundColor',[1 1 1]);
        %position(3)=1.20*position(3);
        position(4)=1.50*position(4);
        set(h,'Position',position);
    case 'popupmenu'
    case 'listbox'
        position(3)=extent(3)+extent(4);
        string=get(h,'String');
        if iscell(string)
            N=numel(string);
        else
            N=1;
        end
        position(4)=N*extent(4);
        set(h,'String','');
        extent=get(h,'Extent');
        position(4)=position(4)-N*extent(4);
        set(h,'Position',position);
    case 'slider'
        parent=get(h,'Parent');
        color=get(parent,'Color');
        set(h,'BackgroundColor',color);
end
% deal with fractional pixels
pos=getpixelposition(h);
setpixelposition(h,ceil(pos));
% handle output
if nargout>=1
    varargout{1}=h;
end
end