Description of EditBoxNum2Str
Home > .. > SMASHtoolbox > programs > PointVISAR > private > EditBoxNum2Str.m
EditBoxNum2Str
PURPOSE
SYNOPSIS
function func=EditBoxNum2Str(number)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
formatG FORMATG Returns a format string using %g compatible with
This function is called by:
ReadEditRecordGUI read/edit records for PointVISARGUI
SaveConfig SaveConfig Save current PointVISAR configuration to file.
SOURCE CODE
function func=EditBoxNum2Str(number)
sigfigs=6;
format=formatG(sigfigs);
func='';
for ii=1:numel(number)
    temp=sprintf(format,number(ii));
    temp=sscanf(temp,'%s');
    if ii == 1
        func = [func temp];
    else
        func=[func ' ' temp];
    end
end