Description of LoadConfig
Home > .. > SMASHtoolbox > programs > PointVISAR > private > LoadConfig.m
LoadConfig
PURPOSE
LoadConfig Loads a PointVISAR configuration file.
SYNOPSIS
function [data,status]=LoadConfig(filename)
DESCRIPTION
   LoadConfig  Loads a PointVISAR configuration file.
CROSS-REFERENCE INFORMATION
This function calls:
DistinguishedLines
InterpConfig InterpConfig : interpret a configuration file
ParseConfig parseconfig : parse configuration file
VisarAnalysis VisarAnalysis Provides a gateway to different stages of Visar
This function is called by:
PointVISARGUI PointVISARGUI
SOURCE CODE
%   LoadConfig  Loads a PointVISAR configuration file.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [data,status]=LoadConfig(filename)
% input check
if nargin<1
    filename='';
end
% parse the configuration file
[data,status,filename]=ParseConfig(filename);
if isempty(data)
    return
end
% interpret the configuration file
[data,status]=InterpConfig(data,filename);
% process each record
for ii=1:length(data)
    % Analyze each record
    data{ii}=VisarAnalysis(data{ii});
    % set administrative
    data{ii}.NewRecord=false;
    data{ii}.LineColor=DistinguishedLines(ii);
end