Description of PointVISARversion
Home > .. > SMASHtoolbox > programs > PointVISAR > private > PointVISARversion.m
PointVISARversion
PURPOSE
PointVISARversion : returns current PointVISAR version number
SYNOPSIS
function [version,versiondate]=PointVISARversion()
DESCRIPTION
 PointVISARversion : returns current PointVISAR version number
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
AboutPointVISAR
CommandLineHelp %%%%%%%%%%%%%%%%%%%%%%%%%
SaveConfig SaveConfig Save current PointVISAR configuration to file.
SOURCE CODE
% PointVISARversion : returns current PointVISAR version number
function [version,versiondate]=PointVISARversion()
%Version history:
%    Version 2.1 created May 17, 2005
%    Version 2.2 created May 31, 2005
%    Version 2.5 created October 15, 2008
%         -bug fixes and Windows executable generated August 29, 2009
% First release beta
% version='2.3';
% versiondate='July 7, 2005';
% First Sandia release
%version='2.3.1';
%versiondate='July 14, 2005';
% First general release
%version='2.5';
%versiondate='September 2009';
% Final release?
%version='2.6';
%versiondate='August 2010';
% added support for Agilent HDF5 files
version='2.6C';
%versiondate='April 2012';
versiondate='August 2020';