% installSMASH Install SMASH toolbox 
%
% To install the SMASH toolbox, launch this function from the toolbox
% directory.
%    installSMASH
% A warning is generated if the toolbox is already installed.  To bypass
% this warning and reinstall the toolbox, type:
%    installSMASH -force
% Installation makes the toolbox available to the current MATLAB
% session.  A startup file (for future sessions) is also created unless one
% already exists; instructions for modifying the startup file are printed
% in the command window for the latter case.
%
% To uninstall the toolbox, type:
%    installSMASH -remove  
%
% See also SMASHtoolbox
%

%
% created March 27, 2018 by Daniel Dolan (Sandia National Laboratories)
%    -This utility can be used on any system, but it's particlarly useful
%    in situations where path changes cannot be saved because the user does
%    not have write permission to the root MATLAB directory.
%
function installSMASH(mode)

%% manage input
if (nargin < 1) || strcmpi(mode,'-standard')
    mode='-standard';
elseif strcmpi(mode,'-force') || strcmpi(mode,'-remove')
    mode=lower(mode);
else
    error('ERROR: invalid mode');
end

%% check installation status
start=pwd;
cd(tempdir);
try   
    existing=smashroot();
    installed=true;
catch
    installed=false;
end
cd(start);

%% use specified mode
switch mode
    case '-standard'
        msg{1}='ERROR: toolbox already installed';
        msg{end+1}='Use "installSMASH -force" to reinstall';
        assert(~installed,'%s\n',msg{:});
        installToolbox();
    case '-force'
        removeToolbox(existing);
        installToolbox();
    case '-remove'
        assert(installed,...
            'ERROR: cannot remove toolbox because it is not installed');
        fprintf('Are you sure about removing the SMASH toolbox?\n');
        choice=input('(y)es or (n)o : ','s');
        switch lower(choice)
            case {'y' 'yes'}
                removeToolbox(existing);
        end      
end

end

%%
function installToolbox()

% move unzipped toolbox (Git repositories stay where they are)
start=pwd;
folder=fullfile(start,'.git');
if ~exist(folder,'dir')
    fprintf('Moving toolbox files to:\n');
    new=fullfile(userpath(),'SMASHtoolbox');
    fprintf('   %s\n',new);
    fprintf('Press return to accept or type an alternate location\n');
    choice=input('location : ','s');
    if ~isempty(choice)
        new=choice;
    end
    cd ..
    try
        %movefile(start,new,'f');
        copyfile(start,new,'f');
        cd(new);
        cd ..
    catch
        cd(start);
        error('ERROR: invalid location');
    end
end

fprintf('Adding toolbox to MATLAB path...');
addpath(smashroot());
fprintf('done\n');
command=sprintf('addpath(''%s'');',smashroot());

file=which('startup.m');
if isempty(file)
    fprintf('Creating startup file for future sessions...');
    userpath('reset');
    fid=fopen(fullfile(userpath(),'startup.m'),'w');
    fprintf(fid,'%% Startup function generated by installSMASH %s\n',...
        datestr(now));
    fprintf(fid,'function startup()\n');
    fprintf(fid,'\n');
    fprintf(fid,'%s\n',command);
    fprintf(fid,'\n');
    fprintf(fid,'end\n');
    fclose(fid);
    fprintf('done\n');
else
    fprintf('Add this command:\n');
    fprintf('   %s\n',command);
    fprintf('to the startup file located:\n');
    fprintf('   %s\n',file);
    fprintf('to use SMASH in future sessions.\n\n');
    choice=input('Edit startup file now? (y)es or (n)o : ','s');
    switch lower(choice)
        case {'y' 'yes'}
            edit(file);
    end
end

end

%%
function removeToolbox(existing)

old=path;
start=1;
stop=regexp(old,pathsep);
new='';
for k=1:(numel(stop)+1)
    if k < numel(stop)
        temp=old(start:(stop(k)-1));
        start=stop(k)+1;
    else
        temp=old(start:end);
    end
    if regexp(temp,existing)
        continue
    else
        new=[new pathsep temp]; %#ok<AGROW>
    end
end
path(new);

end