Description of make_signals
Home > .. > SMASHtoolbox > programs > fringen > private > make_signals.m
make_signals
PURPOSE
SYNOPSIS
function data=make_signals(data)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
PDVfringen apply default parameters where necessary
VISARfringen apply default parameters where necessary
This function is called by:
PDVparamsGUI
VISARparamsGUI
fringenGUI
SOURCE CODE
function data=make_signals(data)
if ~isfield(data,'mode')
    data.mode='VISAR';
end
if ~isfield(data,'params')
    data.params=struct();
end
switch upper(data.mode)
    case 'PDV'
        data=PDVfringen(data);
    case 'VISAR'
        data=VISARfringen(data);
    otherwise
        fprintf('%s is not a valid mode',data.mode);
end