% This class produces a basic graphical interface.  The minimalist design
% of this interface allows it be be useful across different
% hardware/sofware systems.  The design combines elements that resizable
% elements (things that scale with figure size) with fixed elements.
%
% To generate a new graphical interface:
%    object=BasicGUI(...)
% where input arguments are passed to the Figure class.  Creating this
% object generates new MATLAB figure containing three things: a panel for
% axes object, a panel for push buttons, and a custom toolbar (generated by
% the Figure class).  No menus are associated with the figure, though they
% can be added as necessary.  
%
% A panel for push buttons is located at the bottom of the figure.  The
% axes panel is located directly above the button panel.  Most of the
% figure is allocated to the axes panel; the button panel is only as large
% as needed to contain the defined buttons.
%
% See also SMASH.MUI, Figure

%
% created December 2, 2015 by Daniel Dolan (Sandia National Laboratories)
%
classdef BasicGUI < handle
    %%
    properties (SetAccess=private)        
        Figure % Figure object
        AxesPanel % Axes panel handle
        AxesObject % Axes object handle(s)
        ButtonPanel % Button panel handle
        ButtonObject % Button object handle(s)
    end
    %%
    properties (SetAccess=private,Hidden=true)
        BPwidth = 0 % Button panel width [pixels]
        BPheight = 0 % Button panel height [pixels]      
        BPmargin = 20 % Button panel margin (button spacing) [pixels]
    end
    %%
    methods (Hidden=true)
        function object=BasicGUI(varargin)
            % create objects
           object.Figure=SMASH.MUI.Figure(varargin{:});
           set(object.Figure.Handle,'Color','w','NumberTitle','off');
           object.AxesPanel=uipanel('Parent',object.Figure.Handle,...
               'Tag','AxesPanel','Visible','on',...
               'Units','normalized','Position',[0 0 1 1],...
               'BorderType','none',...
               'BackgroundColor',get(object.Figure.Handle,'Color')); 
           object.ButtonPanel=uipanel('Parent',object.Figure.Handle,...
               'Tag','BottomPanel','Visible','on',...
               'BorderType','none',...
               'BackgroundColor',get(object.Figure.Handle,'Color'));
           % set up resize function
           temp=@(src,edata) resize(object,src,edata);
           set(object.Figure.Handle,'ResizeFcn',temp);
        end
        varargout=resize(varargin);
    end
    %%
    methods (Hidden=true)
        %varargout=addlistener(varargin);
        varagout=eq(varargin);
        varargout=findobj(varargin);
        varargout=findprop(varargin);
        varagout=ge(varargin);
        varagout=gt(varargin);
        %varagout=isvalid(varargin);
        varagout=le(varargin);
        varagout=lt(varargin);
        varagout=ne(varargin);
        varagout=notify(varargin);
    end
end