Description of clean_legend
Home > .. > SMASHtoolbox > programs > THRIVE > private > clean_legend.m
clean_legend
PURPOSE
clean_legend : eliminates duplicate tag information in legend
SYNOPSIS
function varargout=clean_legend(varargin)
DESCRIPTION
 clean_legend : eliminates duplicate tag information in legend
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ClonePlot get handles
LoadScreen LoadScreen:
QuadratureScreen this function needs to be significantly revised. Entry into the figure
SOURCE CODE
% clean_legend : eliminates duplicate tag information in legend
function varargout=clean_legend(varargin)
[legend_h,object_h,plot_h,text_strings]=legend(varargin{:});
set(object_h,'Tag',''); % remove legend tags (avoids multiple tag issues)
% handle output
if nargout>0
    varargout{1}=legend_h;
end
if nargout>1
    varargout{2}=object_h;
end
if nargout>2
    varargout{3}=plot_h;
end
if nargout>3
    varargout{4}=text_strings;
end