Description of editbox
Home > .. > SMASHtoolbox > programs > THRIVE > private > editbox.m
editbox
PURPOSE
SYNOPSIS
function [h,pos]=editbox(parent,pos,string,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
custom_uicontrol customized uicontrol function
This function is called by:
EllipseScreen allocate mising input
LoadScreen LoadScreen:
MinimalFigure MinimalFigure: create a minimalistic figure useful for GUIs
ResultsScreen ResultsScreen:
SOURCE CODE
function [h,pos]=editbox(parent,pos,string,varargin)
if isempty(pos)
    pos=[1 1];
end
[h,posA]=custom_uicontrol('Parent',parent,'Style','edit','String',string);
pos=[pos(1:2) posA(3:4)];
set(h,'Position',pos,varargin{:});
set(h,'BackgroundColor',[1 1 1]);