Description of MatchFigures
Home > .. > SMASHtoolbox > programs > THRIVE > private > MatchFigures.m
MatchFigures
PURPOSE
match the position of two figures
SYNOPSIS
function MatchFigures(old,new)
DESCRIPTION
 match the position of two figures
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EllipseScreen allocate mising input
LoadScreen LoadScreen:
QuadratureScreen this function needs to be significantly revised. Entry into the figure
ResultsScreen ResultsScreen:
SOURCE CODE
% match the position of two figures
function MatchFigures(old,new)
% probe old figure size (pixels)
units=get(old,'Units');
set(old,'Units','pixels');
pos=get(old,'Position');
set(old,'Units',units);
% set new figure size (pixels)
units=get(new,'Units');
set(new,'Position',pos,'Units',units);