Description of NudgeTextBoxes
Home > .. > SMASHtoolbox > programs > THRIVE > private > NudgeTextBoxes.m
NudgeTextBoxes
PURPOSE
SYNOPSIS
function NudgeTextBoxes(fig)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EllipseScreen allocate mising input
LoadScreen LoadScreen:
QuadratureScreen this function needs to be significantly revised. Entry into the figure
ResultsScreen ResultsScreen:
SOURCE CODE
function NudgeTextBoxes(fig)
h=findobj(fig,'Type','uicontrol','Style','text');
for k=1:numel(h)
    string=get(h(k),'String');
    set(h(k),'String','');
    pos=get(h(k),'Position');
    extent=get(h(k),'Extent');
    pos(2)=pos(2)-2*extent(4);
    set(h(k),'Position',pos,'String',string);
end