Description of ReadEditBox
Home > .. > SMASHtoolbox > programs > THRIVE > private > ReadEditBox.m
ReadEditBox
PURPOSE
read edit box callback
SYNOPSIS
function data=ReadEditBox(src,varargin)
DESCRIPTION
 read edit box callback
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EllipseScreen allocate mising input
LoadScreen LoadScreen:
QuadratureScreen this function needs to be significantly revised. Entry into the figure
ResultsScreen ResultsScreen:
SOURCE CODE
% read edit box callback
function data=ReadEditBox(src,varargin)
entry=get(src,'String');
[data,count,err,next]=sscanf(entry,'%g',1);
if isempty(data) % use stored value for failed read
    data=get(src,'UserData');
    set(src,'String',num2str(data));
else % store new value for successful read
    entry=entry(1:(next-1));
    set(src,'UserData',data,'String',entry);
end