Description of ReadFloatArray
Home > .. > SMASHtoolbox > +SMASH > +FileAccess > @PFFfile > private > ReadFloatArray.m
ReadFloatArray
PURPOSE
SYNOPSIS
function result=ReadFloatArray(fid)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ReadFloat
ReadLong
ReadWord
This function is called by:
readPFTIFL
readPFTNF3
readPFTNG3
readPFTNGD
readPFTNI3
readPFTNV3
readPFTUF1
readPFTUF3
readPFTVTX
SOURCE CODE
function result=ReadFloatArray(fid)
first=ReadWord(fid);
if first==-6 % full float precision
    FOFF10=ReadWord(fid); %#ok<NASGU>
    LENGTH=ReadLong(fid);
    result=fread(fid,LENGTH,'single');
else % reduced float precision
    fseek(fid,-2,'cof');
    OFFSET=ReadFloat(fid);
    SCALE=ReadFloat(fid);
    LENGTH=ReadLong(fid);
    result=ReadWord(fid,LENGTH);
    result=OFFSET+SCALE*result;
end
end