Description of Script
Home > .. > SMASHtoolbox > +SMASH > +System > old > @Script > Script.m
Script
PURPOSE
This class manages the format of MATLAB scripts and their inclusion into
SYNOPSIS
This is a script file.
DESCRIPTION
 This class manages the format of MATLAB scripts and their inclusion into
 the SMASH toolbox.  Refer to the static methods below.
CROSS-REFERENCE INFORMATION
This function calls:
Script This class manages the format of MATLAB scripts and their inclusion into
convert convert Convert between standard and live scripts
extractExample extractExample Extract examples from toolbox
insertExample insertExample Insert example into toolbox
isScript isScript Determine if file is a MATLAB script
showExample manage input
This function is called by:
Script This class manages the format of MATLAB scripts and their inclusion into
SOURCE CODE
% This class manages the format of MATLAB scripts and their inclusion into
% the SMASH toolbox.  Refer to the static methods below.
%
% created January 8, 2018 by Daniel Dolan (Sandia National Laboratories)
%
classdef (Abstract) Script
    methods (Static=true)
        varargout=isScript(varargin)
        varargout=convert(varargin)
        varargout=insertExample(varargin)
        varargout=extractExample(varargin)
        varargout=showExample(varargin);
    end
end