Description of extract_logical
Home > .. > SMASHtoolbox > +SMASH > +FileAccess > @SDAfile > private > extract_logical.m
extract_logical
PURPOSE
SYNOPSIS
function data=extract_logical(archive,setname)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
readAttribute readAttribute Read HDF5 attribute
This function is called by:
extract_cell
extract_structure
SOURCE CODE
function data=extract_logical(archive,setname)
file=archive.ArchiveFile;
empty=readAttribute(file,setname,'Empty');
if strcmp(empty,'yes')
    empty=true;
else
    empty=false;
end
if empty
    data=[];
else
    data=h5read(file,setname);
    data=logical(data);
end
end