% installSMASH Install SMASH toolbox
%
% This function installs the SMASH toolbox.
%    installSMASH
% The user is prompted to accept the default location or specify an
% alternative. A warning is generated if the toolbox is already installed.
% To bypass this warning and reinstall the toolbox, type:
%    installSMASH -force
%
% Installation makes the toolbox available to the current MATLAB
% session.  A startup file (for future sessions) is also created unless one
% already exists; instructions for modifying the startup file are printed
% in the command window for the latter case.
%
% To uninstall the toolbox, type:
%    installSMASH -remove
%
% See also SMASHtoolbox
%

%
% created March 27, 2018 by Daniel Dolan (Sandia National Laboratories)
%    -This utility can be used on any system, but it's particularly useful
%    in situations where path changes cannot be saved because the user does
%    not have write permission to the root MATLAB directory.
%
function installSMASH(mode)

%% manage input
if (nargin < 1) || strcmpi(mode,'-standard')
    mode='-standard';
elseif strcmpi(mode,'-force') || strcmpi(mode,'-remove')
    mode=lower(mode);
else
    error('ERROR: invalid mode');
end

%% check installation status
try
    existing=smashroot();
    installed=true;
catch
    installed=false;
end

temp=mfilename('fullpath');
location=fileparts(fileparts(temp));

%% use specified mode
switch mode
    case '-standard'
        msg{1}='ERROR: toolbox already installed';
        msg{end+1}='Use "installSMASH -force" to overwrite';
        assert(~installed,'%s\n',msg{:});
        installToolbox(location);
    case '-force'
        removeToolbox(existing);
        installToolbox(location);
    case '-remove'
        assert(installed,...
            'ERROR: cannot remove toolbox because it is not installed');
        fprintf('Are you sure about removing the SMASH toolbox?\n');
        choice=input('(y)es or (n)o : ','s');
        switch lower(choice)
            case {'y' 'yes'}
                removeToolbox(existing);
        end
        file=which('startup');
        if ~isempty(file)
            fid=fopen(file,'r');
            number=0;
            while ~feof(fid)
                temp=fgetl(fid);
                number=number+1;
                if any(regexpi(temp,'SMASHtoolbox'))
                    fprintf(2,'Remove toolbox reference on line %d of the startup file\n',number);
                end
            end
            fclose(fid);
        end
end

end

%%
function installToolbox(location)

repo=fullfile(location,'.git');
if exist(repo,'dir') % Git repository
    new=location;
else % ZIP download
    new=fullfile(userpath(),'SMASHtoolbox');
    fprintf('Installing toolbox in:\n');
    fprintf('   %s\n',new);
    fprintf('Press return to accept or type an alternate location\n');
    choice=input('location : ','s');
    if ~isempty(choice)
        new=choice;
    end
    if exist(new,'dir')
        error('ERROR: location already in use. Use  "installSMASH -force to overwrite.');
    end
    try
        copyfile(location,new,'f');
    catch
        error('ERROR: invalid toolbox location');
    end
end

cd(new)
fprintf('Adding toolbox to MATLAB path...');
addpath(smashroot());
fprintf('done\n');
command=sprintf('addpath(''%s'');',smashroot());
userpath('reset');
cd(userpath());

file=which('startup.m');
if isempty(file)
    fprintf('Creating startup file for future sessions...');
    userpath('reset');
    fid=fopen(fullfile(userpath(),'startup.m'),'w');
    fprintf(fid,'%% Startup function generated by installSMASH %s\n',...
        datestr(now));
    fprintf(fid,'function startup()\n');
    fprintf(fid,'\n');
    fprintf(fid,'%s\n',command);
    fprintf(fid,'\n');
    fprintf(fid,'end\n');
    fclose(fid);
    fprintf('done\n');
else
    fprintf('Add this command:\n');
    fprintf('   %s\n',command);
    fprintf('to the startup file located:\n');
    fprintf('   %s\n',file);
    fprintf('to use SMASH in future sessions.\n\n');
    choice=input('Edit startup file now? (y)es or (n)o : ','s');
    switch lower(choice)
        case {'y' 'yes'}
            edit(file);
    end
end

end

%%
function removeToolbox(existing)

old=path;
start=1;
stop=regexp(old,pathsep);
new='';
for k=1:(numel(stop)+1)
    if k < numel(stop)
        temp=old(start:(stop(k)-1));
        start=stop(k)+1;
    else
        temp=old(start:end);
    end
    if regexp(temp,existing)
        continue
    else
        new=[new pathsep temp]; %#ok<AGROW>
    end
end
path(new);

warning off
rmdir(existing,'s');
warning on
userpath('reset');
cd(userpath());

end