% plotContourMatrix Plot contour matrix
%
% Contour matrices are generated by the contourc function, but for whatever
% reason MATLAB provides no way to plot these matrices directly.  This
% function provides this capability in a limited sense.  Each contour is
% rendered as a line object with a unique color.
%
% The standard workflow for this function is as follows.
%    matrix=contourc(...);
%    % matrix manipulations (coordinate transforms, etc.)
%    plotContourMatrix(matrix);
% By default, this function creates a new figure to display contour lines.
% Passing a second input argument allows lines to be drawn in an existing
% axes.
%    plotContourMatrix(matrix,target);
%
% Graphic handles for the contour lines are returned as an output as
% requested.
%    hline=plotContourMatrix(...);
%
% See also SMASH.Graphics, contourc
%

%
% created November 18, 2015 by Daniel Dolan (Sandia National Laboratories)
%
function varargout=plotContourMatrix(Cmatrix,target)

% manage input
if (nargin<2) || isempty(target)
    figure;
    target=axes('Box','on');
end
assert(ishandle(target) && strcmpi(get(target,'Type'),'axes'),...
    'ERROR: invalid target axes');

% generate lines
[data,level]=SMASH.Graphics.contours2lines(Cmatrix);
N=numel(level);
hl=nan(N,1);

for n=1:N
    hl(n)=line('Parent',target,...
        'XData',data{n}(:,1),'YData',data{n}(:,2),...
        'UserData',struct('Level',level(end)),...
        'Tag',sprintf('level=%.6g',level(end)));
end

% assign line colors
new=unique(level);
color=lines(numel(new));
for n=1:numel(hl)
    set(hl(n),'Color',color(level(n)==new,:));
end

% manage output
if nargout>0
    varargout{1}=hl;
end

end